spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  h2:
    console:
      enabled: false


server:
  port: 0
  instance:
    instance-id: "${spring.application.name}:${random.uuid}"