spring:
  datasource:
    url: [URL_DATABASE]
    username: [ TU_USUARIO ]
    password: [ TU_PASSWORD ]

  driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
